      // We only expect an exception if x was not a power of 2.